### ISSUE TITLE
Creating RootAction from `createEmptyAction` and `createPayloadAction`

### ISSUE THREAD

**Issue by rclmenezes** [piotrwitek/react-redux-typescript#10]
Hi,

I stumbled on your code for `createEmptyAction` and `createPayloadAction`. I was making something very similar, but I was having a tough time making RootAction from the results of these functions. You have any luck?

**Comment by rclmenezes** [comment]
I ended up using this pattern:

```
const actionCreators = {
    logout: createEmptyAction('LOGOUT'),
    loginSubmit: createPayloadAction<'LOGIN_SUBMIT', LoginSubmit>('LOGIN_SUBMIT')
}

const actionTypes = {
    logout: returnTypeOf(actionsCreators.logout),
    loginSubmit: returnTypeOf(actionsCreators.loginSubmit),
}
type RootAction = typeof actionTypes[typeof keyof actionTypes];
```

Hacky, but it works pretty well :)

Thanks for making this and `react-redux-typescript-guide`

**Comment by piotrwitek** [comment]
@rclmenezes sorry was really busy, got a better one stay tuned need to sort out my stuff first

**Comment by piotrwitek** [comment]
there is tutorial here with explaining RootAction: https://github.com/piotrwitek/typesafe-actions#tutorial
