### ISSUE TITLE
2.2.0 published in NPM does not contain class ActionCreator

### ISSUE THREAD

**Issue by jbbr** [piotrwitek/react-redux-typescript#3]
2.2.0's tagged code and documentation references the new "ActionCreator" class.
Unfortunately the version published on NPM does not contain this class despite being tagged as 2.2.0 too.

Maybe you accidentally published an older version with the new tag.

**Comment by piotrwitek** [comment]
@jbbr yes you're right, thanks for reporting
Gonna publish the hotfix

**Comment by piotrwitek** [comment]
fixed in https://github.com/piotrwitek/react-redux-typescript/releases/tag/v2.2.1

**Comment by jbbr** [comment]
Thanks for the very quick fix!
